Improve backup/restore script
Former-commit-id: 44e44312fa8c22a3115ac4df9029750d8310f9b0

diff --git a/scripts/restore b/scripts/restore
--- a/scripts/restore
+++ b/scripts/restore
@@ -1,68 +1,89 @@
 #!/bin/bash
 
+set -e
+
 # The parameter $1 is the backup directory location dedicated to the app
 BACKUP_DIR=$1
 
 # The parameter $2 is the id of the app instance ex: strut__2
-APP=$2
+app=$2
 
-domain=$(sudo yunohost app setting $APP domain)
-path=$(sudo yunohost app setting $APP path)
+domain=$(sudo yunohost app setting $app domain)
+path=$(sudo yunohost app setting $app path)
+repo_path=$(sudo yunohost app setting $app repopath)
+db_pwd=$(sudo yunohost app setting $app mysqlpwd)
+adminusername=$(sudo yunohost app setting $app adminusername)
 
-# Check domain/path availability
-sudo yunohost app checkurl $domain$path -a $APP
-if [[ ! $? -eq 0 ]]; then
-    echo "There is already an app on this URL : $domain$path" | sudo tee /dev/stderr
-    exit 1
-fi
-
-# Restore the app files
-final_path=/opt/$APP
-
-if [ -d $final_path ]; then
-    echo "There is already a directory: $final_path " | sudo tee /dev/stderr
-    exit 1
-fi
-sudo cp -a "${BACKUP_DIR}/www" $final_path
-sudo chown -R www-data: $final_path
-
-# Restore the conf files
-conf=/etc/nginx/conf.d/$domain.d/$APP.conf
-if [ -f $conf ]; then
-    echo "There is already a nginx conf file at this path: $conf " | sudo tee /dev/stderr
-    exit 1
-fi
-sudo cp -a "${BACKUP_DIR}/conf/nginx.conf" $conf
-
-# Restore data
-repo_path=$(sudo yunohost app setting $APP repopath)
-sudo cp -a ${BACKUP_DIR}/data/. $repo_path
-
-# Restore mysql dump
-db_pwd=$(sudo yunohost app setting $APP mysqlpwd)
-sudo mysql -u $APP -p$db_pwd $APP < "${BACKUP_DIR}/$APP.dmp"
-
-# Restore dependances (use backport repo for wheezy for golang package)
 if [[ $(cat /etc/debian_version) = "7."* ]]
 then
-    sudo apt-get -y install git
-    sudo echo "deb http://http.debian.net/debian wheezy-backports main" | sudo tee /etc/apt/sources.list.d/debian-backport-tmp.list
-    sudo apt-get update
-    sudo apt-get install -y golang=2:1.3.3-1~bpo70+1 golang-go=2:1.3.3-1~bpo70+1 golang-src=2:1.3.3-1~bpo70+1 golang-doc=2:1.3.3-1~bpo70+1 -V
-    sudo rm /etc/apt/sources.list.d/debian-backport-tmp.list
-    sudo apt-get update
-else
-    sudo apt-get -y install git golang
+    echo "You need debian Jessie (8.x) to install gogs."
+    exit 1
 fi
 
-# Restore users
+# Check domain/path availability
+sudo yunohost app checkurl $domain$path -a $app  \
+    || (echo "Path not available: $domain$path" && exit 1)
+
+# Check that admin user is an existing account
+sudo yunohost user list --json | grep -q "\"username\": \"$adminusername\"" \
+    || (echo "Error: the chosen admin user does not exist" && exit 1)
+
+go version | grep 1.5 || {
+    # Install golang package from jessie backport if necessary
+    sudo echo "deb http://http.debian.net/debian jessie-backports main" | sudo tee /etc/apt/sources.list.d/debian-backport-tmp.list
+    sudo apt-get update
+    sudo apt-get -t jessie-backports -y install golang
+    sudo rm -f /etc/apt/sources.list.d/debian-backport-tmp.list
+    sudo apt-get update
+}
+
+# Add users
 sudo addgroup gogs --system --quiet
 sudo adduser gogs --disabled-login --ingroup gogs --system --quiet --shell /bin/bash
+
+# Restore app files
+final_path=opt/"$app"_src
+sudo mkdir -p $final_path
+sudo cp -a "${BACKUP_DIR}/www" $final_path
+
+# Create directory and link
+sudo mkdir -p /etc/gogs/conf
+sudo mkdir -p /home/gogs/data/avatars
+sudo mkdir -p /var/log/gogs
+sudo ln -fs /etc/gogs $final_path/custom
+sudo ln -fs /home/gogs/data $final_path/data
+sudo ln -fs /var/log/gogs $final_path/log
+sudo ln -s "$final_path"/src/github.com/gogits/gogs opt/"$app"
+
+# Restore conf files
+sudo cp -a "${BACKUP_DIR}/conf/${app}.conf" /etc/nginx/conf.d/$domain.d/$app.conf
+sudo cp -a "${BACKUP_DIR}/conf/app.ini" /etc/gogs/conf/app.ini
+sudo cp -a "${BACKUP_DIR}/conf/gogs" /etc/logrotate.d/gogs
+sudo cp -a "${BACKUP_DIR}/conf/gogs.service" /etc/systemd/system/gogs.service
+
+# Restore data
+sudo cp -a "${BACKUP_DIR}/data/." $repo_path
+
+# Restore gogs home
+sudo cp -a "${BACKUP_DIR}/home/." /home/gogs
+
+# Restore mysql dump
+sudo mysql -u $app -p$db_pwd $app < "${BACKUP_DIR}/$app.dmp"
+
+# Restore permissions
+sudo chown gogs:gogs -R $final_path
+sudo chown -hR gogs:gogs $repo_path
+sudo chown -R gogs:gogs /var/log/gogs
+sudo chown -R gogs:gogs /home/gogs
+sudo chown gogs:gogs $final_path/custom/conf/app.ini
 
 # Add Gogs to YunoHost's monitored services
 sudo yunohost service add gogs --log /var/log/gogs.log
 
-# Reload Nginx
+# Reload/restart services
+sudo service rsyslog restart
+sudo systemctl daemon-reload
+sudo systemctl enable gogs.service
 sudo service nginx reload
 sudo yunohost app ssowatconf
 
